# Convert resources/cacert.pem → include/bnl/cacert_pem.inc as a C byte array.
# Invoked as a build step so the embedded bundle stays in sync with the PEM
# file on disk. The output is a one-liner header that defines:
#
#   static const unsigned char kCaCertPem[]    = { 0x2D, ... };
#   static const std::size_t   kCaCertPemSize  = sizeof(kCaCertPem);
#
# Loaded at startup by tls.cpp via BIO_new_mem_buf + PEM_read_bio_X509.

if(NOT INPUT OR NOT OUTPUT)
    message(FATAL_ERROR "embed_cacert.cmake requires -DINPUT= and -DOUTPUT=")
endif()

# Read the PEM file as hex, then transform "aabbcc..." into
# "0xaa,0xbb,0xcc,...". A single regex pass is ~1000x faster than the
# byte-by-byte CMake loop this replaces (which was spending ~2 minutes
# on the 226 KB cacert.pem because string(SUBSTRING) + math(EXPR) +
# string(APPEND) is interpreted per iteration).
file(READ "${INPUT}" PEM_HEX HEX)
string(LENGTH "${PEM_HEX}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

string(REGEX REPLACE "(..)" ",0x\\1" BYTES "${PEM_HEX}")
string(SUBSTRING "${BYTES}" 1 -1 BYTES)

set(CONTENT
"// Generated by cmake/embed_cacert.cmake — do not edit.
//
// Mozilla CA root bundle, sourced from https://curl.se/ca/cacert.pem and
// embedded into bnl_core at build time. Loaded into every SSL_CTX at
// runtime startup so HTTPS clients (request, web client, tls, native DB
// drivers using TLS) trust standard public CAs without needing a system
// trust store. Update by replacing resources/cacert.pem and rebuilding.

#pragma once

#include <cstddef>

namespace bnl {

inline constexpr unsigned char kCaCertPem[] = {${BYTES}
};

inline constexpr std::size_t kCaCertPemSize = sizeof(kCaCertPem);

}  // namespace bnl
")

file(WRITE "${OUTPUT}" "${CONTENT}")
