# Bake every lib/*.bnl into a single C++ header (`stdlib_embedded.h`) that
# bnl_core includes. The module loader looks up bare-name imports against
# this table after the built-in native modules — so `import "web"` resolves
# to the embedded source of lib/web.bnl with no install step required.
#
# Inputs (set via -D when invoked under `cmake -P`):
#   LIB_DIR  — absolute path to the lib/ directory containing the .bnl files
#   OUT_FILE — absolute path to the header file to (re)write

if(NOT LIB_DIR OR NOT OUT_FILE)
    message(FATAL_ERROR "embed_stdlib.cmake: LIB_DIR and OUT_FILE must be set")
endif()

file(GLOB lib_files "${LIB_DIR}/*.bnl")
list(SORT lib_files)

set(content "// Auto-generated by cmake/embed_stdlib.cmake — do not edit.\n")
string(APPEND content "// Regenerated whenever any lib/*.bnl source changes.\n")
string(APPEND content "#pragma once\n\n")
string(APPEND content "#include <string>\n")
string(APPEND content "#include <unordered_map>\n\n")
string(APPEND content "namespace bnl {\n\n")
string(APPEND content
    "inline const std::unordered_map<std::string, std::string>& embedded_stdlib() {\n")
string(APPEND content
    "    static const std::unordered_map<std::string, std::string> table = {\n")

foreach(file ${lib_files})
    get_filename_component(name "${file}" NAME_WE)
    file(READ "${file}" src)
    # Raw string literal with a delimiter unlikely to appear in user source.
    string(APPEND content "        { \"${name}\", R\"BNL_EMBED(${src})BNL_EMBED\" },\n")
endforeach()

string(APPEND content "    };\n")
string(APPEND content "    return table;\n")
string(APPEND content "}\n\n")
string(APPEND content "}  // namespace bnl\n")

file(WRITE "${OUT_FILE}" "${content}")
