# Generates a C++ header that embeds every lib/*.bnl source as a raw string
# keyed by its basename (without extension).
#
# Required variables (passed via -D on the cmake command line):
#   OUT  - absolute path to the header file to write
#   LIB  - absolute path to the lib/ directory holding *.bnl sources

if(NOT DEFINED OUT OR NOT DEFINED LIB)
    message(FATAL_ERROR "embed_stdlib.cmake requires -DOUT=<header> and -DLIB=<lib dir>")
endif()

file(GLOB STDLIB_FILES "${LIB}/*.bnl")

set(content "// AUTOGENERATED by cmake/embed_stdlib.cmake — do not edit.\n")
string(APPEND content "#pragma once\n\n")
string(APPEND content "#include <string_view>\n")
string(APPEND content "#include <unordered_map>\n\n")
string(APPEND content "namespace bnl {\n\n")
string(APPEND content "// Returns a name->source map of every lib/*.bnl shipped inside bnl.exe.\n")
string(APPEND content "inline const std::unordered_map<std::string_view, std::string_view>& embedded_stdlib() {\n")
string(APPEND content "    static const std::unordered_map<std::string_view, std::string_view> map = {\n")

foreach(f ${STDLIB_FILES})
    get_filename_component(name "${f}" NAME_WE)
    file(READ "${f}" src)
    # Use a long custom raw-string delimiter so we won't collide with anything
    # a developer might write inside a .bnl file.
    string(APPEND content "        {\"${name}\", R\"BNLSTDLIB29F8(${src})BNLSTDLIB29F8\"},\n")
endforeach()

string(APPEND content "    };\n")
string(APPEND content "    return map;\n")
string(APPEND content "}\n\n")
string(APPEND content "}  // namespace bnl\n")

file(WRITE "${OUT}" "${content}")
