# Convert resources/cacert.pem → include/bnl/cacert_pem.inc as a C byte array.
# Invoked as a build step so the embedded bundle stays in sync with the PEM
# file on disk. The output is a one-liner header that defines:
#
#   static const unsigned char kCaCertPem[]    = { 0x2D, ... };
#   static const std::size_t   kCaCertPemSize  = sizeof(kCaCertPem);
#
# Loaded at startup by tls.cpp via BIO_new_mem_buf + PEM_read_bio_X509.

if(NOT INPUT OR NOT OUTPUT)
    message(FATAL_ERROR "embed_cacert.cmake requires -DINPUT= and -DOUTPUT=")
endif()

# Read the PEM file as hex.
file(READ "${INPUT}" PEM_HEX HEX)

string(LENGTH "${PEM_HEX}" HEX_LEN)
math(EXPR BYTE_COUNT "${HEX_LEN} / 2")

# Build a {0x2D, 0x2D, ...} literal. Newlines every 16 bytes for readability.
set(BYTES "")
set(I 0)
set(COL 0)
while(I LESS HEX_LEN)
    string(SUBSTRING "${PEM_HEX}" ${I} 2 HEX_BYTE)
    if(COL EQUAL 0)
        set(BYTES "${BYTES}\n    ")
    endif()
    set(BYTES "${BYTES}0x${HEX_BYTE},")
    math(EXPR I   "${I} + 2")
    math(EXPR COL "(${COL} + 1) % 16")
endwhile()

set(CONTENT
"// Generated by cmake/embed_cacert.cmake — do not edit.
//
// Mozilla CA root bundle, sourced from https://curl.se/ca/cacert.pem and
// embedded into bnl_core at build time. Loaded into every SSL_CTX at
// runtime startup so HTTPS clients (request, web client, tls, native DB
// drivers using TLS) trust standard public CAs without needing a system
// trust store. Update by replacing resources/cacert.pem and rebuilding.

#pragma once

#include <cstddef>

namespace bnl {

inline constexpr unsigned char kCaCertPem[] = {${BYTES}
};

inline constexpr std::size_t kCaCertPemSize = sizeof(kCaCertPem);

}  // namespace bnl
")

file(WRITE "${OUTPUT}" "${CONTENT}")
